site_name: Intelligent Textbook
site_url: https://btlepak.github.io/ITv1
site_author: Benjamin Lepak
site_description: "Intelligent Textbook of 4061 Introduction to Operating Systems, using material from Advanced Programming in the UNIX Environment, Third Edition, by W. Richard Stevens and Stephen A. Rago, 2013."
repo_url: "https://github.com/btlepak/Intelligent-Textbook-v2"
copyright: "Psinder is licensed under the <a href='https://github.com/michaeltlombardi/mkdocs-psinder/blob/master/LICENSE.md'>MIT license</a>"
theme: psinder
nav:
    - Home: index.md
    - Specimen: specimen.md
    - Configuration: configuration.md
extra:
    version: 0.4.0
    repo_branch: dev
    disqus: psinder
use_directory_urls: false